### ISSUE TITLE
建议同步到 texstudio-org/texstudio/completion

### ISSUE THREAD

**Issue by zepinglee** [hot123tea123/texstudio-cwl#1]
我注意到 [texstudio-org/texstudio/completion](https://github.com/texstudio-org/texstudio/tree/master/completion) 还缺乏 `ctex.cwl`、`xeCJK.cwl` 等文件，而且 texstudio 的 [`completion/unicode-math.cwl`](https://github.com/texstudio-org/texstudio/blob/master/completion/unicode-math.cwl) 是 @muzimuzhi 写的，建议合并到 texstudio 的主项目里更方便大家使用。

另外，最原始的项目是 https://github.com/LaTeXing/LaTeX-cwl ，然而似乎不如 [texstudio-org/texstudio/completion](https://github.com/texstudio-org/texstudio/tree/master/completion) 活跃。

**Comment by muzimuzhi** [comment]
- 根据项目介绍，https://github.com/LaTeXing/LaTeX-cwl 对应 Sublime Text 2/3 的拓展
 - 当前项目，对应 texstudio
 - texstudio 拓展了 Sublime Text 2/3 cwl 的语法，而且在缓慢增加。所以当前项目很可能没法合并进 `LaTeXing/LaTeX-cwl` 了。

------
 - `xeCJK.cwl` 及 `unicode-math.cwl` 的支持，我原计划先实现 https://github.com/texstudio-org/texstudio/issues/902 ，然而懒掉了。因为 https://github.com/texstudio-org/texstudio/issues/1250 ，`unicode-math.cwl` 提前加入了。
 - `ctex` 宏集部分，因为目前 `cwl` 对多层或嵌套 key-val 的自动补全没什么支持，能做的有限，所以我也拖着了。要加的话，涉及修改 https://github.com/texstudio-org/texstudio/blob/master/completion/cwlAliases.dat 。

**Comment by zepinglee** [comment]
我主要是比较关心 LaTeX-Workshop（因为我用的是 VS Code），目前的是从 https://github.com/LaTeXing/LaTeX-cwl 转换的（见 [LaTeX-Workshop/data](https://github.com/James-Yu/LaTeX-Workshop/tree/master/data#files-inside-packages) ），而且 https://github.com/James-Yu/LaTeX-Workshop/issues/2098#issuecomment-630789190 还提到了 texstudio 是 GPL 协议，不能用于 MIT 协议的 LaTeX-Workshop。

**Comment by muzimuzhi** [comment]
如 https://github.com/James-Yu/LaTeX-Workshop/issues/2098#issuecomment-630789190 隐晦提到的，`LaTeXing/LaTeX-cwl` 项目虽然没有说明开源协议，但因为它里面相当部分的 cwl 是从 texstudio 继承过来的，如果严格遵循 GPL，那么 `LaTeX-Workshop` 已经「被污染」了。

https://github.com/LaTeXing/LaTeX-cwl 项目目前包含 217 个 cwl 文件，其中 85 个是由  commit message 里明确提到 `add xxx from https://github.com/texstudio-org/texstudio/` 的三个提交
 - https://github.com/LaTeXing/LaTeX-cwl/commit/5094502a9ee0d482f203099d2c144214fca33705
 - https://github.com/LaTeXing/LaTeX-cwl/commit/7f3f891ac852bbda3e06ea36eaee91c75c3f1844
 - https://github.com/LaTeXing/LaTeX-cwl/commit/b02f56d7a614152d47dcb8d7ea3fa3055036282c

创建的。

如果只是要让 latex-workshop 支持 ctex 和 xecjk，提供带完整参数的命令列表就行了。可以跳过 texsdutio 的部分（cwl 里的不少标记信息，latex-workshop 也用不到）。

**Comment by hubutui** [comment]
你们谁有兴趣合并就合并呗，我已经很久不用了这个了．目前也没有兴趣和精力去搞这个．

**Comment by zepinglee** [comment]
@muzimuzhi 请教一下 https://github.com/texstudio-org/texstudio/blob/61bfca7d929f7041a96aaeb64231ad8166a67290/completion/fontspec.cwl#L18 这里以「*」结尾，跟「#*」结尾有什么区别？我在 txs 的 manual 里没找到「*」的说明。

**Comment by muzimuzhi** [comment]
@zepinglee [TeXstudio User Manual](https://htmlpreview.github.io/?https://github.com/texstudio-org/texstudio/master/utilities/manual/usermanual_en.html), Sec. 4.14.3 Classification format, 

> Classifier | Meaning
> -- | --
> \* | unusual command which is used for completion only in with the "all" tab. This marker may be followed by other classifications.

对 hubutui：内容稍微离题，抱歉打扰。

**Comment by zepinglee** [comment]
https://github.com/texstudio-org/texstudio/pull/1455 merged.
